### ISSUE TITLE
Error in new version

### ISSUE THREAD

**Issue by zwhitchcox** [AgilionApps/remix#15]
I get this error:

```
16:24:12.324 [error] GenServer Remix.Worker terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1636: Enum.reduce/3
    (elixir) lib/enum.ex:2346: Enum.to_list/1
    (elixir) lib/map.ex:104: Map.new/2
    (remix) lib/remix.ex:31: Remix.Worker.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
Last message: :poll_and_reload
State: %{}
```

when compiling from source.

**Comment by harlantwood** [comment]
fixed in #16
